# Production profile
# spring.profiles.active=prod

# Production DB settings

spring.profiles.active=prod

spring.datasource.url=jdbc:postgresql://postgres:vQrIiKwvucqgaSoCskbErKSuOnVzBrJm@postgres.railway.internal:5432/railway
spring.datasource.username=postgres
spring.datasource.password=vQrIiKwvucqgaSoCskbErKSuOnVzBrJm

spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true (optional for debugging)
