# ========================
# PRODUCTION PROFILE (prod)
# ========================
spring.config.activate.on-profile=prod
spring.datasource.url=jdbc:postgresql://postgres.vQrIiKwvucqgaSoCskbErKSuOnVzBrJm@postgres.railway.internal:5432/railway
spring.datasource.username=postgres
spring.datasource.password=vQrIiKwvucqgaSoCskbErKSuOnVzBrJm
spring.jpa.show-sql=false