spring.application.name=demo


spring.datasource.url=jdbc:postgresql://localhost:5432/manytomany
spring.datasource.username=postgres
spring.datasource.password=Shakti
# spring.datasource.password=ishan!1
# spring.datasource.password=Sulav_1552
spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

