# Production profile DB settings
spring.datasource.url=jdbc:postgresql://postgres.railway.internal:5432/railway?user=postgres&password=vQrIiKwvucqgaSoCskbErKSuOnVzBrJm
spring.datasource.username=postgres
spring.datasource.password=vQrIiKwvucqgaSoCskbErKSuOnVzBrJm
spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true (optional for debugging)
