spring.application.name=demo
server.port=8065

# Set active profile using environment variable
# spring.profiles.active=${ENV:dev}


spring.datasource.url=jdbc:postgresql://localhost:5432/manytomany
spring.datasource.username=postgres
spring.datasource.password=Shakti


spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

