# ========================
# DEVELOPMENT PROFILE (dev)
# ========================
spring.config.activate.on-profile=dev
spring.datasource.url=jdbc:postgresql://localhost:5432/manytomany
spring.datasource.username=postgres
spring.datasource.password=Shakti
spring.jpa.show-sql=true
